### ISSUE TITLE
Selfbotting is against Discord ToS.

### ISSUE THREAD

**Issue by Purpzie** [Merubokkusu/discord-spam-bots#10]
You might want to include this image in the readme. Otherwise, people are going to blame you for getting their accounts banned soon after using the bot.

![](https://cdn.discordapp.com/attachments/81384788765712384/374827488171261953/unknown.png)

I hardly believe that the bot is for "testing" but hey, as long as people are warned first, I think GitHub allows it to be here.

**Comment by Merubokkusu** [comment]
I actually had it on my last repository.

I also deleted my last one because of the amount of messages I received from server owners saying their server was raided and assumed it was from this script.

Originally it was made for joking around with friends, then I just started adding tons of features and realized how easy it was to get past discords anti-spam so it became a matter of "how much I can do". Personally I make this for testing anti-spam. (As I'm an admin on a server with over 900 users)
